version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mds-mailer
      - DB_NAME=mds-mailer
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
